on:
  push:
    branches:
      - main
name: Deploy cultivesmart on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2
      
    - name: Use Node.js 18
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        
    - name: Build project
      run: |
        npm install
        npm run build
        
    - name: List output files
      run: find dist/ -print
      
    - name: Sync files
      uses: SamKirland/FTP-Deploy-Action@4.1.0
      with:
        server: 46.202.145.116
        username: u746034674
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: dist/